namespace Alimatic.DataDin.Models
{
    public class FilaApiModel
    {
        public int Id { get; set; }
        public int ModeloId { get; set; }
        public string Descripcion { get; set; }

        public static FilaApiModel[] Filas { get; } = new FilaApiModel[]
        {
            #region 5920
            new FilaApiModel { Id = 1, ModeloId = 5920, Descripcion = "Activos Circulantes" },
            new FilaApiModel { Id = 2, ModeloId = 5920, Descripcion = "Efectivo en Caja (101-108)" },
            new FilaApiModel { Id = 3, ModeloId = 5920, Descripcion = "Efectivo en Banco y en Otras Instituciones (109-119)" },
            new FilaApiModel { Id = 4, ModeloId = 5920, Descripcion = "Inversiones a Corto Plazo o Temporales (120-129)" },
            new FilaApiModel { Id = 5, ModeloId = 5920, Descripcion = "Efectos por Cobrar a Corto Plazo (130-133)" },
            new FilaApiModel { Id = 6, ModeloId = 5920, Descripcion = "Menos: Efectos por Cobrar Descontados (365)" },
            new FilaApiModel { Id = 7, ModeloId = 5920, Descripcion = "Cuenta en Participación (134)" },
            new FilaApiModel { Id = 8, ModeloId = 5920, Descripcion = "Cuentas por Cobrar a Corto Plazo (135-139 y 154)" },
            new FilaApiModel { Id = 9, ModeloId = 5920, Descripcion = "Menos: Provisión para Cuentas Incobrables (369)" },
            new FilaApiModel { Id = 10, ModeloId = 5920, Descripcion = "Pagos por Cuenta de Terceros (140)" },
            new FilaApiModel { Id = 11, ModeloId = 5920, Descripcion = "Participación de Reaseguradores por Siniestros Pendientes (141)" },
            new FilaApiModel { Id = 12, ModeloId = 5920, Descripcion = "Préstamos y Otras Operaciones Crediticias a Cobrar a Corto Plazo (142)" },
            new FilaApiModel { Id = 13, ModeloId = 5920, Descripcion = "Suscriptores de Bonos (143)" },
            new FilaApiModel { Id = 14, ModeloId = 5920, Descripcion = "Pagos Anticipados a Suministradores (146-149)" },
            new FilaApiModel { Id = 15, ModeloId = 5920, Descripcion = "Pagos Anticipados del Proceso Inversionista (150-152)" },
            new FilaApiModel { Id = 16, ModeloId = 5920, Descripcion = "Materiales Anticipados del Proceso Inversionista (153)" },
            new FilaApiModel { Id = 17, ModeloId = 5920, Descripcion = "Anticipos a Justificar (161-163)" },
            new FilaApiModel { Id = 18, ModeloId = 5920, Descripcion = "Adeudos del Presupuesto del Estado (164-166)" },
            new FilaApiModel { Id = 19, ModeloId = 5920, Descripcion = "Adeudos del Órgano u Organismo (167-170)" },
            new FilaApiModel { Id = 20, ModeloId = 5920, Descripcion = "Ingresos Acumulados por Cobrar (173-180)" },
            new FilaApiModel { Id = 21, ModeloId = 5920, Descripcion = "Dividendos y Participaciones por Cobrar (181)" },
            new FilaApiModel { Id = 22, ModeloId = 5920, Descripcion = "Ingresos Acumulados por Cobrar – Reaseguros Aceptados (182)" },
            new FilaApiModel { Id = 23, ModeloId = 5920, Descripcion = "Total de Inventarios" },
            new FilaApiModel { Id = 24, ModeloId = 5920, Descripcion = "Materias Primas y Materiales (183)" },
            new FilaApiModel { Id = 25, ModeloId = 5920, Descripcion = "Combustibles y Lubricantes (184)" },
            new FilaApiModel { Id = 26, ModeloId = 5920, Descripcion = "Partes y Piezas de Repuesto (185)" },
            new FilaApiModel { Id = 27, ModeloId = 5920, Descripcion = "Envases y Embalajes (186)" },
            new FilaApiModel { Id = 28, ModeloId = 5920, Descripcion = "Útiles, Herramientas y Otros (187)" },
            new FilaApiModel { Id = 29, ModeloId = 5920, Descripcion = "Menos: Desgaste de Útiles y Herramientas (373)" },
            new FilaApiModel { Id = 30, ModeloId = 5920, Descripcion = "Producción Terminada (188)" },
            new FilaApiModel { Id = 31, ModeloId = 5920, Descripcion = "Mercancías para la Venta (189)" },
            new FilaApiModel { Id = 32, ModeloId = 5920, Descripcion = "Menos: Descuento Comercial e Impuesto (370-372)" },
            new FilaApiModel { Id = 33, ModeloId = 5920, Descripcion = "Medicamentos (190)" },
            new FilaApiModel { Id = 34, ModeloId = 5920, Descripcion = "Base Material de Estudio (191)" },
            new FilaApiModel { Id = 35, ModeloId = 5920, Descripcion = "Menos: Desgaste de Base Material de Estudio (366)" },
            new FilaApiModel { Id = 36, ModeloId = 5920, Descripcion = "Vestuario y Lencería (192)" },
            new FilaApiModel { Id = 37, ModeloId = 5920, Descripcion = "Menos: Desgaste de Vestuario y Lencería (367)" },
            new FilaApiModel { Id = 38, ModeloId = 5920, Descripcion = "Alimentos (193)" },
            new FilaApiModel { Id = 39, ModeloId = 5920, Descripcion = "Inventarios de Mercancías de Importación (194)" },
            new FilaApiModel { Id = 40, ModeloId = 5920, Descripcion = "Inventarios de Mercancías de Exportación (195)" },
            new FilaApiModel { Id = 41, ModeloId = 5920, Descripcion = "Producciones  para Insumo o Autoconsumo (196)" },
            new FilaApiModel { Id = 42, ModeloId = 5920, Descripcion = "Otros Inventarios (205-207)" },
            new FilaApiModel { Id = 43, ModeloId = 5920, Descripcion = "Inventarios Ociosos (208)" },
            new FilaApiModel { Id = 44, ModeloId = 5920, Descripcion = "Inventarios de Lento Movimiento (209)" },
            new FilaApiModel { Id = 45, ModeloId = 5920, Descripcion = "Producción en Proceso (700-724)" },
            new FilaApiModel { Id = 46, ModeloId = 5920, Descripcion = "Producción Propia para Insumos (725)" },
            new FilaApiModel { Id = 47, ModeloId = 5920, Descripcion = "Reparaciones Capitales con Medios Propios (726)" },
            new FilaApiModel { Id = 48, ModeloId = 5920, Descripcion = "Inversiones con Medios Propios Activos Fijos Intangibles (727)" },
            new FilaApiModel { Id = 49, ModeloId = 5920, Descripcion = "Inversiones con Medios Propios (728)" },
            new FilaApiModel { Id = 50, ModeloId = 5920, Descripcion = "Créditos Documentarios (211)" },
            new FilaApiModel { Id = 51, ModeloId = 5920, Descripcion = "Activos a Largo Plazo" },
            new FilaApiModel { Id = 52, ModeloId = 5920, Descripcion = "Efectos por Cobrar a Largo Plazo (215-217)" },
            new FilaApiModel { Id = 53, ModeloId = 5920, Descripcion = "Cuentas por Cobrar a Largo Plazo (218-220)" },
            new FilaApiModel { Id = 54, ModeloId = 5920, Descripcion = "Préstamos Concedidos a Cobrar a Largo Plazo (221-224)" },
            new FilaApiModel { Id = 55, ModeloId = 5920, Descripcion = "Inversiones a Largo Plazo o Permanentes (225-234)" },
            new FilaApiModel { Id = 56, ModeloId = 5920, Descripcion = "Activos Fijos" },
            new FilaApiModel { Id = 57, ModeloId = 5920, Descripcion = "Activos Fijos Tangibles (240-251)" },
            new FilaApiModel { Id = 58, ModeloId = 5920, Descripcion = "Menos: Depreciación de Activos Fijos Tangibles (375-388)" },
            new FilaApiModel { Id = 59, ModeloId = 5920, Descripcion = "Fondos Bibliotecarios (252)" },
            new FilaApiModel { Id = 60, ModeloId = 5920, Descripcion = "Medios y Equipos para Alquilar (253)" },
            new FilaApiModel { Id = 61, ModeloId = 5920, Descripcion = "Menos: Desgaste de Medios y Equipos para Alquilar (389)" },
            new FilaApiModel { Id = 62, ModeloId = 5920, Descripcion = "Monumentos y Obras de Arte (254)" },
            new FilaApiModel { Id = 63, ModeloId = 5920, Descripcion = "Activos Fijos Intangibles (255 – 263)" },
            new FilaApiModel { Id = 64, ModeloId = 5920, Descripcion = "Activos Fijos Intangibles en Proceso (264)" },
            new FilaApiModel { Id = 65, ModeloId = 5920, Descripcion = "Menos: Amortización de Activos Fijos Intangibles (390-399)" },
            new FilaApiModel { Id = 66, ModeloId = 5920, Descripcion = "Inversiones en Proceso (265-278)" },
            new FilaApiModel { Id = 67, ModeloId = 5920, Descripcion = "Plan de Preparación de Inversiones (279)" },
            new FilaApiModel { Id = 68, ModeloId = 5920, Descripcion = "Equipos por Instalar y Materiales para el Proceso Inversionista (280-289)" },
            new FilaApiModel { Id = 69, ModeloId = 5920, Descripcion = "Activos Diferidos" },
            new FilaApiModel { Id = 70, ModeloId = 5920, Descripcion = "Gastos de Producción y Servicios Diferidos (300-305)" },
            new FilaApiModel { Id = 71, ModeloId = 5920, Descripcion = "Gastos Financieros Diferidos (306-307)" },
            new FilaApiModel { Id = 72, ModeloId = 5920, Descripcion = "Gastos del Proceso Inversionista Diferidos (310-311)" },
            new FilaApiModel { Id = 73, ModeloId = 5920, Descripcion = "Gastos por Faltantes y Pérdidas Diferidos (312)" },
            new FilaApiModel { Id = 74, ModeloId = 5920, Descripcion = "Otros Activos" },
            new FilaApiModel { Id = 75, ModeloId = 5920, Descripcion = "Pérdidas en Investigación (330-331)" },
            new FilaApiModel { Id = 76, ModeloId = 5920, Descripcion = "Faltantes de Bienes en Investigación (332-333)" },
            new FilaApiModel { Id = 77, ModeloId = 5920, Descripcion = "Cuentas por Cobrar Diversas – Operaciones Corrientes (334-341)" },
            new FilaApiModel { Id = 78, ModeloId = 5920, Descripcion = "Cuentas por Cobrar – Compra de Monedas (342)" },
            new FilaApiModel { Id = 79, ModeloId = 5920, Descripcion = "Cuentas por Cobrar del Proceso Inversionista (343-345)" },
            new FilaApiModel { Id = 80, ModeloId = 5920, Descripcion = "Efectos por Cobrar en Litigio (346)" },
            new FilaApiModel { Id = 81, ModeloId = 5920, Descripcion = "Cuentas por Cobrar en Litigio (347)" },
            new FilaApiModel { Id = 82, ModeloId = 5920, Descripcion = "Efectos por Cobrar Protestados (348)" },
            new FilaApiModel { Id = 83, ModeloId = 5920, Descripcion = "Cuentas por Cobrar en Proceso Judicial (349)" },
            new FilaApiModel { Id = 84, ModeloId = 5920, Descripcion = "Depósitos y Fianzas (354-355)" },
            new FilaApiModel { Id = 85, ModeloId = 5920, Descripcion = "Fondo de Amortización de Bonos – Efectivo y Valores (364)" },
            new FilaApiModel { Id = 86, ModeloId = 5920, Descripcion = "Menos: Otras Provisiones Reguladoras de Activos (374)" },
            new FilaApiModel { Id = 87, ModeloId = 5920, Descripcion = "TOTAL DEL ACTIVO" },
            new FilaApiModel { Id = 88, ModeloId = 5920, Descripcion = "Pasivos Circulantes" },
            new FilaApiModel { Id = 89, ModeloId = 5920, Descripcion = "Sobregiro Bancario (400)" },
            new FilaApiModel { Id = 90, ModeloId = 5920, Descripcion = "Efectos por Pagar a Corto Plazo (401-404)" },
            new FilaApiModel { Id = 91, ModeloId = 5920, Descripcion = "Cuentas por Pagar a Corto Plazo (405-415)" },
            new FilaApiModel { Id = 92, ModeloId = 5920, Descripcion = "Cobros por Cuenta de Terceros (416)" },
            new FilaApiModel { Id = 93, ModeloId = 5920, Descripcion = "Dividendos y Participaciones por Pagar (417)" },
            new FilaApiModel { Id = 94, ModeloId = 5920, Descripcion = "Cuentas en Participación (418-420)" },
            new FilaApiModel { Id = 95, ModeloId = 5920, Descripcion = "Cuentas por Pagar - Activos Fijos Tangibles (421-424)" },
            new FilaApiModel { Id = 96, ModeloId = 5920, Descripcion = "Cuentas por Pagar del Proceso Inversionista (425-429)" },
            new FilaApiModel { Id = 97, ModeloId = 5920, Descripcion = "Cobros Anticipados (430-433)" },
            new FilaApiModel { Id = 98, ModeloId = 5920, Descripcion = "Materiales Recibidos de Forma Anticipada (434)" },
            new FilaApiModel { Id = 99, ModeloId = 5920, Descripcion = "Depósitos Recibidos (435-439)" },
            new FilaApiModel { Id = 100, ModeloId = 5920, Descripcion = "Obligaciones con el Presupuesto del Estado (440-449)" },
            new FilaApiModel { Id = 101, ModeloId = 5920, Descripcion = "Obligaciones con el Órgano u Organismo (450-453)" },
            new FilaApiModel { Id = 102, ModeloId = 5920, Descripcion = "Nóminas por Pagar (455-459)" },
            new FilaApiModel { Id = 103, ModeloId = 5920, Descripcion = "Retenciones por Pagar (460-469)" },
            new FilaApiModel { Id = 104, ModeloId = 5920, Descripcion = "Préstamos Recibidos y Otras Operaciones Crediticias por Pagar (470-479)" },
            new FilaApiModel { Id = 105, ModeloId = 5920, Descripcion = "Gastos Acumulados por Pagar (480-489)" },
            new FilaApiModel { Id = 106, ModeloId = 5920, Descripcion = "Provisión para Vacaciones (492)" },
            new FilaApiModel { Id = 107, ModeloId = 5920, Descripcion = "Otras Provisiones Operacionales (493-499)" },
            new FilaApiModel { Id = 108, ModeloId = 5920, Descripcion = "Provisión para Pagos de los Subsidios de Seguridad Social a Corto Plazo (500)" },
            new FilaApiModel { Id = 109, ModeloId = 5920, Descripcion = "Fondo de Compensación para Desbalances Financieros (501) uso exclusivo de las OSDE" },
            new FilaApiModel { Id = 110, ModeloId = 5920, Descripcion = "Pasivos a Largo Plazo" },
            new FilaApiModel { Id = 111, ModeloId = 5920, Descripcion = "Efectos por Pagar a Largo Plazo (510-514)" },
            new FilaApiModel { Id = 112, ModeloId = 5920, Descripcion = "Cuentas por Pagar a Largo Plazo (515-518)" },
            new FilaApiModel { Id = 113, ModeloId = 5920, Descripcion = "Préstamos Recibidos por Pagar a Largo Plazo (520-524)" },
            new FilaApiModel { Id = 114, ModeloId = 5920, Descripcion = "Obligaciones a Largo Plazo (525-532)" },
            new FilaApiModel { Id = 115, ModeloId = 5920, Descripcion = "Otras Provisiones a Largo Plazo (533-539)" },
            new FilaApiModel { Id = 116, ModeloId = 5920, Descripcion = "Bonos por Pagar (540)-(144)-(363)" },
            new FilaApiModel { Id = 117, ModeloId = 5920, Descripcion = "Bonos Suscritos (541)" },
            new FilaApiModel { Id = 118, ModeloId = 5920, Descripcion = "Pasivos Diferidos" },
            new FilaApiModel { Id = 119, ModeloId = 5920, Descripcion = "Ingresos Diferidos (545-548)" },
            new FilaApiModel { Id = 120, ModeloId = 5920, Descripcion = "Ingresos Diferidos por Donaciones Recibidas (549)" },
            new FilaApiModel { Id = 121, ModeloId = 5920, Descripcion = "Otros Pasivos" },
            new FilaApiModel { Id = 122, ModeloId = 5920, Descripcion = "Sobrantes en Investigación (555-564)" },
            new FilaApiModel { Id = 123, ModeloId = 5920, Descripcion = "Cuentas por Pagar Diversas (565-568)" },
            new FilaApiModel { Id = 124, ModeloId = 5920, Descripcion = "Cuentas por Pagar – Compra de Monedas (569)" },
            new FilaApiModel { Id = 125, ModeloId = 5920, Descripcion = "Ingresos de Períodos Futuros (570-574)" },
            new FilaApiModel { Id = 126, ModeloId = 5920, Descripcion = "Obligación con el Presupuesto del Estado por Garantía Activada (575)" },
            new FilaApiModel { Id = 127, ModeloId = 5920, Descripcion = "TOTAL DEL PASIVO" },
            new FilaApiModel { Id = 128, ModeloId = 5920, Descripcion = "Inversión Estatal (600-612) Sector Público" },
            new FilaApiModel { Id = 129, ModeloId = 5920, Descripcion = "Patrimonio y Fondo Común (600) Sector Privado" },
            new FilaApiModel { Id = 130, ModeloId = 5920, Descripcion = "Capital Social Suscrito y Pagado" },
            new FilaApiModel { Id = 131, ModeloId = 5920, Descripcion = "Recursos Recibidos (617-618) Sector Público" },
            new FilaApiModel { Id = 132, ModeloId = 5920, Descripcion = "Donaciones Recibidas – Nacionales (620)" },
            new FilaApiModel { Id = 133, ModeloId = 5920, Descripcion = "Donaciones Recibidas – Exterior (621)" },
            new FilaApiModel { Id = 134, ModeloId = 5920, Descripcion = "Utilidades Retenidas (630-634)" },
            new FilaApiModel { Id = 135, ModeloId = 5920, Descripcion = "Subvención por Pérdida (635-639)" },
            new FilaApiModel { Id = 136, ModeloId = 5920, Descripcion = "Reservas para Contingencias (645)" },
            new FilaApiModel { Id = 137, ModeloId = 5920, Descripcion = "Otras Reservas Patrimoniales (646-654)" },
            new FilaApiModel { Id = 138, ModeloId = 5920, Descripcion = "Fondo de Contravalor para proyectos de Inversión (688)" },
            new FilaApiModel { Id = 139, ModeloId = 5920, Descripcion = "Menos: Recursos Entregados (619) Sector Público" },
            new FilaApiModel { Id = 140, ModeloId = 5920, Descripcion = "Donaciones Entregadas –Nacionales (626)" },
            new FilaApiModel { Id = 141, ModeloId = 5920, Descripcion = "Donaciones Entregadas – Exterior (627)" },
            new FilaApiModel { Id = 142, ModeloId = 5920, Descripcion = "Pago a Cuenta de las Utilidades (690)" },
            new FilaApiModel { Id = 143, ModeloId = 5920, Descripcion = "Pago a Cuenta de los Dividendos (691)" },
            new FilaApiModel { Id = 144, ModeloId = 5920, Descripcion = "Pérdida (640-644)" },
            new FilaApiModel { Id = 145, ModeloId = 5920, Descripcion = "Más o Menos: Revalorización de Activos Fijos Tangibles (613 - 615)" },
            new FilaApiModel { Id = 146, ModeloId = 5920, Descripcion = "Otras Operaciones de Capital (616 - 619) Sector Privado" },
            new FilaApiModel { Id = 147, ModeloId = 5920, Descripcion = "Revaluación de Inventarios (697)" },
            new FilaApiModel { Id = 148, ModeloId = 5920, Descripcion = "Ganancia o Pérdida no Realizada (698)" },
            new FilaApiModel { Id = 149, ModeloId = 5920, Descripcion = "Resultado del Período" },
            new FilaApiModel { Id = 150, ModeloId = 5920, Descripcion = "TOTAL DE PATRIMONIO NETO" },
            new FilaApiModel { Id = 151, ModeloId = 5920, Descripcion = "TOTAL DEL PASIVO Y PATRIMONIO NETO O CAPITAL CONTABLE" },
            #endregion

            #region 5921
            new FilaApiModel { Id = 1, ModeloId = 5921, Descripcion = "Ventas (900 - 913)" },
            new FilaApiModel { Id = 2, ModeloId = 5921, Descripcion = "Más: Ventas de Bienes con destino a la Exportación (914)" },
            new FilaApiModel { Id = 3, ModeloId = 5921, Descripcion = "Ventas  por Exportación de Servicios (915)" },
            new FilaApiModel { Id = 4, ModeloId = 5921, Descripcion = "Subvenciones (916 - 919)" },
            new FilaApiModel { Id = 5, ModeloId = 5921, Descripcion = "Menos: Devoluciones y Rebajas en Ventas (800 – 804)" },
            new FilaApiModel { Id = 6, ModeloId = 5921, Descripcion = "Impuesto por las Ventas (805 – 809)" },
            new FilaApiModel { Id = 7, ModeloId = 5921, Descripcion = "Ventas Netas" },
            new FilaApiModel { Id = 8, ModeloId = 5921, Descripcion = "Menos: Costo de Ventas de la Producción (810 – 813)" },
            new FilaApiModel { Id = 9, ModeloId = 5921, Descripcion = "Costo de Ventas de Mercancías (814 – 817)" },
            new FilaApiModel { Id = 10, ModeloId = 5921, Descripcion = "Costo por Exportación de Servicios (818)" },
            new FilaApiModel { Id = 11, ModeloId = 5921, Descripcion = "Utilidad o Pérdida Bruta en Ventas" },
            new FilaApiModel { Id = 12, ModeloId = 5921, Descripcion = "Menos: Gastos de Distribución y Ventas (819 – 821)" },
            new FilaApiModel { Id = 13, ModeloId = 5921, Descripcion = "Utilidad o Pérdida Neta en Ventas" },
            new FilaApiModel { Id = 14, ModeloId = 5921, Descripcion = "Menos: Gastos Generales y de Administración (822 – 824)" },
            new FilaApiModel { Id = 15, ModeloId = 5921, Descripcion = "Gastos de Operación (826 – 833)" },
            new FilaApiModel { Id = 16, ModeloId = 5921, Descripcion = "Gastos de Administración de la OSDE (834)" },
            new FilaApiModel { Id = 17, ModeloId = 5921, Descripcion = "Utilidad o Pérdida en Operaciones" },
            new FilaApiModel { Id = 18, ModeloId = 5921, Descripcion = "Menos: Gastos de Proyectos (825)" },
            new FilaApiModel { Id = 19, ModeloId = 5921, Descripcion = "Gastos Financieros (835 – 838)" },
            new FilaApiModel { Id = 20, ModeloId = 5921, Descripcion = "Gastos por Pérdidas en Tasa de Cambio (839)" },
            new FilaApiModel { Id = 21, ModeloId = 5921, Descripcion = "Financiamiento Entregado a la OSDE (840)" },
            new FilaApiModel { Id = 22, ModeloId = 5921, Descripcion = "Gastos por Estadía – Importadores (841)" },
            new FilaApiModel { Id = 23, ModeloId = 5921, Descripcion = "Gastos por Estadía – Otras Entidades (843)" },
            new FilaApiModel { Id = 24, ModeloId = 5921, Descripcion = "Gastos por Pérdidas (845 – 848)" },
            new FilaApiModel { Id = 25, ModeloId = 5921, Descripcion = "Gastos por Pérdidas-Desastres (849)" },
            new FilaApiModel { Id = 26, ModeloId = 5921, Descripcion = "Gastos por Faltantes de Bienes (850 – 854)" },
            new FilaApiModel { Id = 27, ModeloId = 5921, Descripcion = "Otros Impuestos, Tasas y Contribuciones (855-864)" },
            new FilaApiModel { Id = 28, ModeloId = 5921, Descripcion = "Otros Gastos (865 – 866)" },
            new FilaApiModel { Id = 29, ModeloId = 5921, Descripcion = "Gastos de Eventos (867)" },
            new FilaApiModel { Id = 30, ModeloId = 5921, Descripcion = "Gastos de Recuperación de Desastres (873)" },
            new FilaApiModel { Id = 31, ModeloId = 5921, Descripcion = "Más: Ingresos Financieros (920 – 922)" },
            new FilaApiModel { Id = 32, ModeloId = 5921, Descripcion = "Financiamiento Recibido de las Empresas (923)" },
            new FilaApiModel { Id = 33, ModeloId = 5921, Descripcion = "Ingresos por Variación de Tasa de Cambio (924)" },
            new FilaApiModel { Id = 34, ModeloId = 5921, Descripcion = "Ingresos por Dividendos Ganados (925)" },
            new FilaApiModel { Id = 35, ModeloId = 5921, Descripcion = "Ingresos por Estadía (navieras y operadores) (926– 927)" },
            new FilaApiModel { Id = 36, ModeloId = 5921, Descripcion = "Ingresos por Recobro de Estadía (importadores y otras entidades) (928 – 929)" },
            new FilaApiModel { Id = 37, ModeloId = 5921, Descripcion = "Ingresos por Sobrantes  (930 – 939)" },
            new FilaApiModel { Id = 38, ModeloId = 5921, Descripcion = "Otros Ingresos (950 – 952)" },
            new FilaApiModel { Id = 39, ModeloId = 5921, Descripcion = "Ingresos por Donaciones Recibidas (953)" },
            new FilaApiModel { Id = 40, ModeloId = 5921, Descripcion = "Utilidad o Pérdida antes del Impuesto." },
            #endregion

            #region 5924
            new FilaApiModel { Id = 1, ModeloId = 5924, Descripcion = "Materias Primas y Materiales" },
            new FilaApiModel { Id = 2, ModeloId = 5924, Descripcion = "Combustibles y Lubricantes" },
            new FilaApiModel { Id = 3, ModeloId = 5924, Descripcion = "Energía" },
            new FilaApiModel { Id = 4, ModeloId = 5924, Descripcion = "Salario" },
            new FilaApiModel { Id = 5, ModeloId = 5924, Descripcion = "De ellos: Salario Escala" },
            new FilaApiModel { Id = 6, ModeloId = 5924, Descripcion = "Pagos Adicional del Perfeccionamiento Empresarial" },
            new FilaApiModel { Id = 7, ModeloId = 5924, Descripcion = "Otros Pagos Adicionales" },
            new FilaApiModel { Id = 8, ModeloId = 5924, Descripcion = "Pago por Resultado" },
            new FilaApiModel { Id = 9, ModeloId = 5924, Descripcion = "Acumulación de Vacaciones (9.09%)" },
            new FilaApiModel { Id = 10, ModeloId = 5924, Descripcion = "Depreciación y Amortización" },
            new FilaApiModel { Id = 11, ModeloId = 5924, Descripcion = "Otros Gastos Monetarios" },
            new FilaApiModel { Id = 12, ModeloId = 5924, Descripcion = "De ellos: Servicios Comprados entre entidades" },
            new FilaApiModel { Id = 13, ModeloId = 5924, Descripcion = "Servicios de Mantenimiento y Reparación Constructivo" },
            new FilaApiModel { Id = 14, ModeloId = 5924, Descripcion = "Reparación y Mantenimiento de Viales" },
            new FilaApiModel { Id = 15, ModeloId = 5924, Descripcion = "Otros Servicios de Mantenimiento y Reparaciones Corrientes" },
            new FilaApiModel { Id = 16, ModeloId = 5924, Descripcion = "Gastos por importación de servicios" },
            new FilaApiModel { Id = 17, ModeloId = 5924, Descripcion = "Viáticos" },
            new FilaApiModel { Id = 18, ModeloId = 5924, Descripcion = "TOTAL DE GASTOS POR ELEMENTOS" },
            #endregion

            #region 5925
            new FilaApiModel { Id = 1, ModeloId = 5925, Descripcion = "SECCIÓN I : INVERSIONES" },
            new FilaApiModel { Id = 2, ModeloId = 5925, Descripcion = "Inversiones en Proceso (265 – 278)" },
            new FilaApiModel { Id = 3, ModeloId = 5925, Descripcion = "Construcción y Montaje (0010)" },
            new FilaApiModel { Id = 4, ModeloId = 5925, Descripcion = "Equipos (0020)" },
            new FilaApiModel { Id = 5, ModeloId = 5925, Descripcion = "Otros Gastos (0030)" },
            new FilaApiModel { Id = 6, ModeloId = 5925, Descripcion = "Fomentos Agrícolas (0050)" },
            new FilaApiModel { Id = 7, ModeloId = 5925, Descripcion = "Fomentos y Desarrollo Mineros (0060)" },
            new FilaApiModel { Id = 8, ModeloId = 5925, Descripcion = "Fomentos y Desarrollo Forestales (0070)" },
            new FilaApiModel { Id = 9, ModeloId = 5925, Descripcion = "Otros No Especificados (0100)" },
            new FilaApiModel { Id = 10, ModeloId = 5925, Descripcion = "Fondo de Fomento Desarrollo Ganadero (0200)" },
            new FilaApiModel { Id = 11, ModeloId = 5925, Descripcion = "Plan de preparación de inversiones (279 - 0010, 0020, 0030)" },
            new FilaApiModel { Id = 12, ModeloId = 5925, Descripcion = "Adquisición de Activos Fijos Tangibles Nuevos (290 – 0100 y 0300)" },
            new FilaApiModel { Id = 13, ModeloId = 5925, Descripcion = "Compra de Activos Fijos Tangibles de Uso (291 – 0100 y 0300)" },
            new FilaApiModel { Id = 14, ModeloId = 5925, Descripcion = "Compra de Activos Fijos Intangibles (292 – 0100 y 0300)" },
            new FilaApiModel { Id = 15, ModeloId = 5925, Descripcion = "SECCIÓN II: INVERSIONES FINANCIERAS" },
            new FilaApiModel { Id = 16, ModeloId = 5925, Descripcion = "Inversiones a Largo Plazo o Permanentes (225 – 234)" },
            #endregion

            #region 5926
            new FilaApiModel { Id = 1, ModeloId = 5926, Descripcion = "Ventas o Ingresos Netos" },
            new FilaApiModel { Id = 2, ModeloId = 5926, Descripcion = "Más: Financiamiento Recibido de las Empresas (923)" },
            new FilaApiModel { Id = 3, ModeloId = 5926, Descripcion = "Más: Saldo de la Cuenta Producción en Proceso (700 – 724)" },
            new FilaApiModel { Id = 4, ModeloId = 5926, Descripcion = "Menos: Saldo de la Cuenta Producción en Proceso al Inicio del Año (700 – 724)" },
            new FilaApiModel { Id = 5, ModeloId = 5926, Descripcion = "Más: Saldo de la Cuenta Producción Terminada (188)" },
            new FilaApiModel { Id = 6, ModeloId = 5926, Descripcion = "Menos: Saldo de la Cuenta Producción Terminada al Inicio del Año (188)" },
            new FilaApiModel { Id = 7, ModeloId = 5926, Descripcion = "Menos: Aumento de la existencia de Producción Terminada por conceptos distintos al de producción y entrega (188 – 0040)" },
            new FilaApiModel { Id = 8, ModeloId = 5926, Descripcion = "Más: Disminución de la existencia de Producción Terminada por conceptos distintos al de producción y entrega (188 – 0050)" },
            new FilaApiModel { Id = 9, ModeloId = 5926, Descripcion = "Más: Gastos diferidos del período relacionados con procesos productivos y de servicios (300 – 305 – 0020)" },
            new FilaApiModel { Id = 10, ModeloId = 5926, Descripcion = "Más: Gastos del período de las producciones destinadas al insumo (725 – 0020)" },
            new FilaApiModel { Id = 11, ModeloId = 5926, Descripcion = "Más: Saldo de las cuentas de Otros Ingresos e Ingresos Financieros (Excepto variación de tasas de cambio y los dividendos) (920 – 922 + 950 – 952)" },
            new FilaApiModel { Id = 12, ModeloId = 5926, Descripcion = "Menos: Gastos incorporados a las producciones en proceso proveniente del almacén de las producciones de insumo o autoconsumo (196 – 0030)" },
            new FilaApiModel { Id = 13, ModeloId = 5926, Descripcion = "Más: Gastos del período de Reparaciones Capitales con Medios Propios (726 – 0020)" },
            new FilaApiModel { Id = 14, ModeloId = 5926, Descripcion = "Más: Gastos del período de las Inversiones con Medios Propios Activos Fijos Intangibles (727 - 0020)" },
            new FilaApiModel { Id = 15, ModeloId = 5926, Descripcion = "Más: Gastos del período por Inversiones con Medios Propios (728 – 0020)" },
            new FilaApiModel { Id = 16, ModeloId = 5926, Descripcion = "Menos: Saldo de la cuenta Costo de Ventas de Mercancías (814 – 817)" },
            new FilaApiModel { Id = 17, ModeloId = 5926, Descripcion = "PRODUCCIÓN DE BIENES Y SERVICIOS" },
            new FilaApiModel { Id = 18, ModeloId = 5926, Descripcion = "Gasto Material" },
            new FilaApiModel { Id = 19, ModeloId = 5926, Descripcion = "Otros Gastos Monetarios" },
            new FilaApiModel { Id = 20, ModeloId = 5926, Descripcion = "Financiamiento entregado a la OSDE (840)" },
            new FilaApiModel { Id = 21, ModeloId = 5926, Descripcion = "CONSUMO INTERMEDIO" },
            new FilaApiModel { Id = 22, ModeloId = 5926, Descripcion = "VALOR AGREGADO BRUTO CREADO" },
            #endregion
        };
    }
}
