// <auto-generated />
using Alimatic.DataDin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Alimatic.DataDin.Data.Migrations
{
    [DbContext(typeof(DataDinDbContext))]
    [Migration("00000000000000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Alimatic.DataDin.Models.Division", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Divisiones");
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Empresa", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("DivisionId");

                    b.Property<int>("GrupoId");

                    b.Property<string>("Nombre")
                        .HasMaxLength(32);

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(127);

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("NombreCompleto")
                        .IsUnique();

                    b.HasIndex("DivisionId", "GrupoId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.EstadoFinanciero", b =>
                {
                    b.Property<int>("Año");

                    b.Property<int>("Mes");

                    b.Property<int>("EmpresaId");

                    b.Property<int>("ModeloId");

                    b.Property<int>("FilaId");

                    b.Property<decimal>("C1")
                        .HasColumnType("Decimal(22, 2)");

                    b.Property<decimal>("C2")
                        .HasColumnType("Decimal(22, 2)");

                    b.Property<decimal>("C3")
                        .HasColumnType("Decimal(22, 2)");

                    b.HasKey("Año", "Mes", "EmpresaId", "ModeloId", "FilaId");

                    b.HasAlternateKey("Año", "EmpresaId", "FilaId", "Mes", "ModeloId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("FilaId", "ModeloId");

                    b.ToTable("EstadosFinancieros");
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Fila", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("ModeloId");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024);

                    b.HasKey("Id", "ModeloId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Filas");
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Grupo", b =>
                {
                    b.Property<int>("DivisionId");

                    b.Property<int>("Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(16);

                    b.HasKey("DivisionId", "Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Modelo", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("CantidadColumnas");

                    b.Property<int>("CantidadFilas");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Empresa", b =>
                {
                    b.HasOne("Alimatic.DataDin.Models.Division", "Division")
                        .WithMany("Empresas")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alimatic.DataDin.Models.Grupo", "Grupo")
                        .WithMany("Empresas")
                        .HasForeignKey("DivisionId", "GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.EstadoFinanciero", b =>
                {
                    b.HasOne("Alimatic.DataDin.Models.Empresa", "Empresa")
                        .WithMany("EstadosFinancieros")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alimatic.DataDin.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alimatic.DataDin.Models.Fila", "Fila")
                        .WithMany()
                        .HasForeignKey("FilaId", "ModeloId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Fila", b =>
                {
                    b.HasOne("Alimatic.DataDin.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Alimatic.DataDin.Models.Grupo", b =>
                {
                    b.HasOne("Alimatic.DataDin.Models.Division", "Division")
                        .WithMany("Grupos")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
