/*
  { Halo.Server } - Sistema Nacional de Vigilancia a la Morbilidad Materna Extremadamente Grave
  Copyright (C) 2017 Halo
  Authors:  Mayli Sanchez
            Yandy Zaldivar
*/

namespace Halo.Models
{
    using Cyxor.Models;

    public class MunicipioApiModel : IdNombreApiModel
    {
        public int Codigo { get; set; }
        public int ProvinciaId { get; set; }

        public static MunicipioApiModel[] Municipios { get; } = new MunicipioApiModel[]
        {
            new MunicipioApiModel { Id = 1, Codigo = 1, Nombre = "Sandino", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 2, Codigo = 2, Nombre = "Mantua", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 3, Codigo = 3, Nombre = "Minas de Matahambre", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 4, Codigo = 4, Nombre = "Viñales", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 5, Codigo = 5, Nombre = "La Palma", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 6, Codigo = 6, Nombre = "Los Palacios", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 7, Codigo = 7, Nombre = "Consolación del Sur", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 8, Codigo = 8, Nombre = "Pinar del Río", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 9, Codigo = 9, Nombre = "San Luis", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 10, Codigo = 10, Nombre = "San Juan y Martínez", ProvinciaId = 1 },
            new MunicipioApiModel { Id = 11, Codigo = 11, Nombre = "Guane", ProvinciaId = 1 },

            new MunicipioApiModel { Id = 12, Codigo = 1, Nombre = "Bahía Honda", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 13, Codigo = 2, Nombre = "Mariel", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 14, Codigo = 3, Nombre = "Guanajay", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 15, Codigo = 4, Nombre = "Caimito", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 16, Codigo = 5, Nombre = "Bauta", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 17, Codigo = 6, Nombre = "San Antonio de los Baños", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 18, Codigo = 7, Nombre = "Güira de Melena", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 19, Codigo = 8, Nombre = "Alquízar", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 20, Codigo = 9, Nombre = "Artemisa", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 21, Codigo = 10, Nombre = "Candelaria", ProvinciaId = 2 },
            new MunicipioApiModel { Id = 22, Codigo = 11, Nombre = "San Cristóbal", ProvinciaId = 2 },

            new MunicipioApiModel { Id = 23, Codigo = 1, Nombre = "Playa", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 24, Codigo = 2, Nombre = "Plaza de la Revolución", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 25, Codigo = 3, Nombre = "Centro Habana", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 26, Codigo = 4, Nombre = "La Habana Vieja", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 27, Codigo = 5, Nombre = "Regla", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 28, Codigo = 6, Nombre = "La Habana del Este", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 29, Codigo = 7, Nombre = "Guanabacoa", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 30, Codigo = 8, Nombre = "San Miguel del Padrón", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 31, Codigo = 9, Nombre = "Diez de Octubre", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 32, Codigo = 10, Nombre = "Cerro", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 33, Codigo = 11, Nombre = "Marianao", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 34, Codigo = 12, Nombre = "La Lisa", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 35, Codigo = 13, Nombre = "Boyeros", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 36, Codigo = 14, Nombre = "Arroyo Naranjo", ProvinciaId = 3 },
            new MunicipioApiModel { Id = 37, Codigo = 15, Nombre = "Cotorro", ProvinciaId = 3 },

            new MunicipioApiModel { Id = 38, Codigo = 1, Nombre = "Bejucal", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 39, Codigo = 2, Nombre = "San José de las Lajas", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 40, Codigo = 3, Nombre = "Jaruco", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 41, Codigo = 4, Nombre = "Santa Cruz del Norte", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 42, Codigo = 5, Nombre = "Madruga", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 43, Codigo = 6, Nombre = "Nueva Paz", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 44, Codigo = 7, Nombre = "San Nicolás", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 45, Codigo = 8, Nombre = "Güines", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 46, Codigo = 9, Nombre = "Melena del Sur", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 47, Codigo = 10, Nombre = "Batabanó", ProvinciaId = 4 },
            new MunicipioApiModel { Id = 48, Codigo = 11, Nombre = "Quivicán", ProvinciaId = 4 },

            new MunicipioApiModel { Id = 49, Codigo = 1, Nombre = "Matanzas", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 50, Codigo = 2, Nombre = "Cárdenas", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 51, Codigo = 3, Nombre = "Martí", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 52, Codigo = 4, Nombre = "Colón", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 53, Codigo = 5, Nombre = "Perico", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 54, Codigo = 6, Nombre = "Jovellanos", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 55, Codigo = 7, Nombre = "Pedro Betancourt", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 56, Codigo = 8, Nombre = "Limonar", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 57, Codigo = 9, Nombre = "Unión de Reyes", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 58, Codigo = 10, Nombre = "Ciénaga de Zapata", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 59, Codigo = 11, Nombre = "Jagüey Grande", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 60, Codigo = 12, Nombre = "Calimete", ProvinciaId = 5 },
            new MunicipioApiModel { Id = 61, Codigo = 13, Nombre = "Los Arabos", ProvinciaId = 5 },

            new MunicipioApiModel { Id = 62, Codigo = 1, Nombre = "Abreus", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 63, Codigo = 2, Nombre = "Aguada de Pasajeros", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 64, Codigo = 3, Nombre = "Cienfuegos", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 65, Codigo = 4, Nombre = "Cruces", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 66, Codigo = 5, Nombre = "Cumanayagua", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 67, Codigo = 6, Nombre = "Lajas", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 68, Codigo = 7, Nombre = "Palmira", ProvinciaId = 6 },
            new MunicipioApiModel { Id = 69, Codigo = 8, Nombre = "Rodas", ProvinciaId = 6 },

            new MunicipioApiModel { Id = 70, Codigo = 1, Nombre = "Corralillo", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 71, Codigo = 2, Nombre = "Quemado de Güines", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 72, Codigo = 3, Nombre = "Sagua la Grande", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 73, Codigo = 4, Nombre = "Encrucijada", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 74, Codigo = 5, Nombre = "Camajuaní", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 75, Codigo = 6, Nombre = "Caibarién", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 76, Codigo = 7, Nombre = "Remedios", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 77, Codigo = 8, Nombre = "Placetas", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 78, Codigo = 9, Nombre = "Santa Clara", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 79, Codigo = 10, Nombre = "Cifuentes", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 80, Codigo = 11, Nombre = "Santo Domingo", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 81, Codigo = 12, Nombre = "Ranchuelo", ProvinciaId = 7 },
            new MunicipioApiModel { Id = 82, Codigo = 13, Nombre = "Manicaragua", ProvinciaId = 7 },

            new MunicipioApiModel { Id = 83, Codigo = 1, Nombre = "Yaguajay", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 84, Codigo = 2, Nombre = "Jatibonico", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 85, Codigo = 3, Nombre = "Taguasco", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 86, Codigo = 4, Nombre = "Cabaiguán", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 87, Codigo = 5, Nombre = "Fomento", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 88, Codigo = 6, Nombre = "Trinidad", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 89, Codigo = 7, Nombre = "Sancti Spíritus", ProvinciaId = 8 },
            new MunicipioApiModel { Id = 90, Codigo = 8, Nombre = "La Sierpe", ProvinciaId = 8 },

            new MunicipioApiModel { Id = 91, Codigo = 1, Nombre = "Chambas", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 92, Codigo = 2, Nombre = "Morón", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 93, Codigo = 3, Nombre = "Bolivia", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 94, Codigo = 4, Nombre = "Primero de Enero", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 95, Codigo = 5, Nombre = "Ciro Redondo", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 96, Codigo = 6, Nombre = "Florencia", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 97, Codigo = 7, Nombre = "Majagua", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 98, Codigo = 8, Nombre = "Ciego de Ávila", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 99, Codigo = 9, Nombre = "Venezuela", ProvinciaId = 9 },
            new MunicipioApiModel { Id = 100, Codigo = 10, Nombre = "Baraguá", ProvinciaId = 9 },

            new MunicipioApiModel { Id = 101, Codigo = 1, Nombre = "Carlos Manuel de Céspedes", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 102, Codigo = 2, Nombre = "Esmeralda", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 103, Codigo = 3, Nombre = "Sierra de Cubitas", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 104, Codigo = 4, Nombre = "Minas", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 105, Codigo = 5, Nombre = "Nuevitas", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 106, Codigo = 6, Nombre = "Guáimaro", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 107, Codigo = 7, Nombre = "Sibanicú", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 108, Codigo = 8, Nombre = "Camagüey", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 109, Codigo = 9, Nombre = "Florida", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 110, Codigo = 10, Nombre = "Vertientes", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 111, Codigo = 11, Nombre = "Jimaguayú", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 112, Codigo = 12, Nombre = "Najasa", ProvinciaId = 10 },
            new MunicipioApiModel { Id = 113, Codigo = 13, Nombre = "Santa Cruz del Sur", ProvinciaId = 10 },

            new MunicipioApiModel { Id = 114, Codigo = 1, Nombre = "Manatí", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 115, Codigo = 2, Nombre = "Puerto Padre", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 116, Codigo = 3, Nombre = "Jesús Menéndez", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 117, Codigo = 4, Nombre = "Majibacoa", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 118, Codigo = 5, Nombre = "Las Tunas", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 119, Codigo = 6, Nombre = "Jobabo", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 120, Codigo = 7, Nombre = "Colombia", ProvinciaId = 11 },
            new MunicipioApiModel { Id = 121, Codigo = 8, Nombre = "Amancio", ProvinciaId = 11 },

            new MunicipioApiModel { Id = 122, Codigo = 1, Nombre = "Gibara", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 123, Codigo = 2, Nombre = "Rafael Freyre", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 124, Codigo = 3, Nombre = "Banes", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 125, Codigo = 4, Nombre = "Antilla", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 126, Codigo = 5, Nombre = "Báguanos", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 127, Codigo = 6, Nombre = "Holguín", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 128, Codigo = 7, Nombre = "Calixto García", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 129, Codigo = 8, Nombre = "Cacocum", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 130, Codigo = 9, Nombre = "Urbano Noris", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 131, Codigo = 10, Nombre = "Cueto", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 132, Codigo = 11, Nombre = "Mayarí", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 133, Codigo = 12, Nombre = "Frank País", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 134, Codigo = 13, Nombre = "Sagua de Tánamo", ProvinciaId = 12 },
            new MunicipioApiModel { Id = 135, Codigo = 14, Nombre = "Moa", ProvinciaId = 12 },

            new MunicipioApiModel { Id = 136, Codigo = 1, Nombre = "Bartolomé Masó", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 137, Codigo = 2, Nombre = "Bayamo", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 138, Codigo = 3, Nombre = "Buey Arriba", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 139, Codigo = 4, Nombre = "Campechuela", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 140, Codigo = 5, Nombre = "Cauto Cristo", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 141, Codigo = 6, Nombre = "Guisa", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 142, Codigo = 7, Nombre = "Jiguaní", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 143, Codigo = 8, Nombre = "Manzanillo", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 144, Codigo = 9, Nombre = "Media Luna", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 145, Codigo = 10, Nombre = "Niquero", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 146, Codigo = 11, Nombre = "Pilón", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 147, Codigo = 12, Nombre = "Río Cauto", ProvinciaId = 13 },
            new MunicipioApiModel { Id = 148, Codigo = 13, Nombre = "Yara", ProvinciaId = 13 },

            new MunicipioApiModel { Id = 149, Codigo = 1, Nombre = "Contramaestre", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 150, Codigo = 2, Nombre = "Guamá", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 151, Codigo = 3, Nombre = "Mella", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 152, Codigo = 4, Nombre = "Palma Soriano", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 153, Codigo = 5, Nombre = "San Luis", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 154, Codigo = 6, Nombre = "Santiago de Cuba", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 155, Codigo = 7, Nombre = "Segundo Frente", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 156, Codigo = 8, Nombre = "Songo-La Maya", ProvinciaId = 14 },
            new MunicipioApiModel { Id = 157, Codigo = 9, Nombre = "Tercer Frente", ProvinciaId = 14 },

            new MunicipioApiModel { Id = 158, Codigo = 1, Nombre = "El Salvador", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 159, Codigo = 2, Nombre = "Manuel Tames", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 160, Codigo = 3, Nombre = "Yateras", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 161, Codigo = 4, Nombre = "Baracoa", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 162, Codigo = 5, Nombre = "Maisí", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 163, Codigo = 6, Nombre = "Imías", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 164, Codigo = 7, Nombre = "San Antonio del Sur", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 165, Codigo = 8, Nombre = "Caimanera", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 166, Codigo = 9, Nombre = "Guantánamo", ProvinciaId = 15 },
            new MunicipioApiModel { Id = 167, Codigo = 10, Nombre = "Niceto Pérez", ProvinciaId = 15 },

            new MunicipioApiModel { Id = 168, Codigo = 1, Nombre = "Nueva Gerona", ProvinciaId = 16 },
        };
    }
}
/* { Halo.Server } */
